require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe JobRolesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # JobRole. As you add validations to JobRole, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # JobRolesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all job_roles as @job_roles" do
      job_role = JobRole.create! valid_attributes
          get :index, params: {}, session: valid_session
          expect(assigns(:job_roles)).to eq([job_role])
    end
  end

  describe "GET #show" do
    it "assigns the requested job_role as @job_role" do
      job_role = JobRole.create! valid_attributes
          get :show, params: {id: job_role.to_param}, session: valid_session
          expect(assigns(:job_role)).to eq(job_role)
    end
  end

  describe "GET #new" do
    it "assigns a new job_role as @job_role" do
          get :new, params: {}, session: valid_session
          expect(assigns(:job_role)).to be_a_new(JobRole)
    end
  end

  describe "GET #edit" do
    it "assigns the requested job_role as @job_role" do
      job_role = JobRole.create! valid_attributes
          get :edit, params: {id: job_role.to_param}, session: valid_session
          expect(assigns(:job_role)).to eq(job_role)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new JobRole" do
        expect {
                  post :create, params: {job_role: valid_attributes}, session: valid_session
                }.to change(JobRole, :count).by(1)
      end

      it "assigns a newly created job_role as @job_role" do
              post :create, params: {job_role: valid_attributes}, session: valid_session
              expect(assigns(:job_role)).to be_a(JobRole)
        expect(assigns(:job_role)).to be_persisted
      end

      it "redirects to the created job_role" do
              post :create, params: {job_role: valid_attributes}, session: valid_session
              expect(response).to redirect_to(JobRole.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved job_role as @job_role" do
              post :create, params: {job_role: invalid_attributes}, session: valid_session
              expect(assigns(:job_role)).to be_a_new(JobRole)
      end

      it "re-renders the 'new' template" do
              post :create, params: {job_role: invalid_attributes}, session: valid_session
              expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested job_role" do
        job_role = JobRole.create! valid_attributes
              put :update, params: {id: job_role.to_param, job_role: new_attributes}, session: valid_session
              job_role.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested job_role as @job_role" do
        job_role = JobRole.create! valid_attributes
              put :update, params: {id: job_role.to_param, job_role: valid_attributes}, session: valid_session
              expect(assigns(:job_role)).to eq(job_role)
      end

      it "redirects to the job_role" do
        job_role = JobRole.create! valid_attributes
              put :update, params: {id: job_role.to_param, job_role: valid_attributes}, session: valid_session
              expect(response).to redirect_to(job_role)
      end
    end

    context "with invalid params" do
      it "assigns the job_role as @job_role" do
        job_role = JobRole.create! valid_attributes
              put :update, params: {id: job_role.to_param, job_role: invalid_attributes}, session: valid_session
              expect(assigns(:job_role)).to eq(job_role)
      end

      it "re-renders the 'edit' template" do
        job_role = JobRole.create! valid_attributes
              put :update, params: {id: job_role.to_param, job_role: invalid_attributes}, session: valid_session
              expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested job_role" do
      job_role = JobRole.create! valid_attributes
      expect {
              delete :destroy, params: {id: job_role.to_param}, session: valid_session
            }.to change(JobRole, :count).by(-1)
    end

    it "redirects to the job_roles list" do
      job_role = JobRole.create! valid_attributes
          delete :destroy, params: {id: job_role.to_param}, session: valid_session
          expect(response).to redirect_to(job_roles_url)
    end
  end

end
